#!/bin/bash

echo "Tarkistetaan ohjelmistopakettien riippuvuudet..."

echo python3-pip
if [[ -z $(dpkg -l|grep  python3-pip) ]]; then
    echo Asennetaan python3-pip
    sudo apt install -y python3-pip
fi

echo "Tarkistetaan Python-pakettien riippuvuudet..."

echo Flask
if [[ -z $(pip3 list|grep "Flask\ ") ]]; then
    echo Asennetaan Flask
    sudo pip3 install flask 
fi

echo Flask-socketio
if [[ -z $(pip3 list|grep "Flask-SocketIO") ]]; then
    echo Asennetaan Flask-socketio
    sudo pip3 install flask_socketio
fi

echo RPi.GPIO
if [[ -z $(pip3 list|grep "Flask-SocketIO") ]]; then
    echo Asennetaan RPi.GPIO
    sudo pip3 install RPi.GPIO
fi


echo Kopioidaan tiedostot...
sudo cp -R src/* /

echo "Sammutetaan palvelu..."
sudo systemctl stop sahkomittari
echo "Käynnistetään palvelu..."
sudo systemctl enable sahkomittari
sudo systemctl start sahkomittari
echo "Asennus valmis!"
