#!/bin/bash

sudo sed -i '/^enable_uart/d' /boot/config.txt #sarjaportti
echo 'enable_uart=1' |sudo tee -a /boot/config.txt >/dev/null #sarjaportti

sudo apt -y install git libgpiod2
rm -rf /tmp/sahkomittari.ini
if [ -f "/opt/sahkomittari/sahkomittari.ini" ]; then
    echo "Tiedosto /opt/sahkomittari/sahkomittari.ini on jo olemassa. Otetaan se talteen!"
    sudo cp /opt/sahkomittari/sahkomittari.ini /tmp/sahkomittari.ini
fi
echo "Tarkistetaan ohjelmistopakettien riippuvuudet..."

echo python3-pip
if [[ -z $(dpkg -l|grep  python3-pip) ]]; then
    echo Asennetaan python3-pip
    sudo apt install -y python3-pip
fi

echo "Tarkistetaan Python-pakettien riippuvuudet..."


echo pyserial
if [[ -z $(pip3 list|grep "pyserial") ]]; then
    echo Asennetaan pyserial
    sudo pip3 install pyserial
fi


echo websocket-client
if [[ -z $(pip3 list|grep "websocket-client") ]]; then
    echo Asennetaan websocket-client
    sudo pip3 install websocket-client

fi

#echo RPi.GPIO
#if [[ -z $(pip3 list|grep "RPi.GPIO") ]]; then
#    echo Asennetaan RPi.GPIO
#    sudo pip3 install RPi.GPIO
#fi

echo adafruit-circuitpython-dht
if [[ -z $(pip3 list|grep "adafruit-circuitpython-dht") ]]; then
    echo Asennetaan adafruit-circuitpython-dht
    sudo pip3 install adafruit-circuitpython-dht
fi

echo Kopioidaan tiedostot...
sudo cp -R src/* /

echo "Sammutetaan palvelu..."
sudo systemctl stop sahkomittari
echo "Käynnistetään palvelu..."
sudo systemctl enable sahkomittari
sudo systemctl start sahkomittari
sudo systemctl daemon-reload

if [ -f "/tmp/sahkomittari.ini" ]; then
    echo "Palautetaan tiedosto /opt/sahkomittari/sahkomittari.ini!"
    sudo mv /tmp/sahkomittari.ini /opt/sahkomittari/sahkomittari.ini
fi

echo "Asennus valmis!"
