#!/bin/bash

sql=$(cat <<EOF
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "asiakkaat" (
        "id"    INTEGER,
        "numero"        TEXT,
        "nimi"  TEXT,
        "ip" TEXT,
        "info"  TEXT,
        PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "kulutus" (
        "id"    INTEGER,
        "numero"        INTEGER,
        "ip" TEXT,
        "kwh"   TEXT,
        "pulssit"       INTEGER,
        PRIMARY KEY("id")
);
COMMIT;
EOF
)
sqlite3 raspisahkomittari.db "$sql"
