#!/bin/bash
date >~/loki
echo "/dev/shm/sahkomittari-server" >>~/loki
ls -lah /dev/shm/sahkomittari-server/ >>~/loki
cat /dev/shm/sahkomittari-server/* >>~/loki
echo "ps ax |grep sahkomittari" >>~/loki
echo "----------------">>~/loki
ps ax |grep sahkomittari >>~/loki
echo "----------------">>~/loki
echo "netstat -a |grep 8888">>~/loki
netstat -a |grep 8888 >>~/loki
echo "----------------">>~/loki
echo "netstat -a |grep 8889">>~/loki
netstat -a |grep 8889 >>~/loki
echo "----LOKIT----">>~/loki
for filename in /var/log/sahkomit*; do
    echo "----------------">>~/loki
    echo "*** $filename" >>~/loki
    cat $filename >>~/loki
done
echo "-------DMESG------"
dmesg -T >>~/loki
cat ~/loki
echo "***** loki on tallennettu tiedostoon $HOME/loki *****"
