#!/bin/bash
mapfile -t  rivit < <(cat /opt/sahkomittari-server/asiakastiedot_tilat/tilat  |tail -n +2) #  |cut -d ';' -f 1)
#echo $rivit
for rivi in "${rivit[@]}"; do
    numero=$(echo $rivi|cut -d ';' -f 1)
    nimi=$(echo $rivi|cut -d ';' -f 2)
    ip=$(echo $rivi|cut -d ';' -f 3)
    ip="${ip::-1}"
    #echo ...$ip...
    if [[ $ip == $1 ]]; then
        echo "$numero-$nimi ($ip)"
    fi
done
