#!/bin/bash
mapfile -t  rivit < <(cat tilat |tail -n +2) #  |cut -d ';' -f 1)
#echo $rivit
for rivi in "${rivit[@]}"; do
    numero=$(echo $rivi|cut -d ';' -f 1)
    nimi=$(echo $rivi|cut -d ';' -f 2)
    ip=$(echo $rivi|cut -d ';' -f 3)
    if [[ $numero == $1 ]]; then
        echo $ip
    fi
done
